server:
  port: 8011

ms:
  clientId: "front1"
  receiverId: "db1"
  serverEndpoint: "ws://localhost:8080/msg-system-endpoint"
  producerEndpoint: "/app/produceMessage"
  subscriptionPrefix: "/topic/consumeMessage"

logging.level.org.springframework.web: DEBUG
